name: focus
description: To be defined
publish_to: 'none'
version: 1.0.1+30

# This represents the flutter sdk accepted versions
# The specific flutter version currently used is 2.6.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Used for icons
  cupertino_icons: ^1.0.3
  # Used for state management
  provider: ^6.0.1
  # Used to make in app payments
  pay: ^1.0.6
  # Launch websites
  url_launcher: ^6.0.20
  # Pay with Stripe
  flutter_stripe: ^2.4.0
  # General database plugin
  firebase_core: ^1.5.0
  # Used to authenticate
  firebase_auth: ^3.0.2
  # Used to store data
  cloud_firestore: ^3.1.4
  # Used to communicate between devices
  firebase_messaging: 11.2.8
  # Used to store profile images
  firebase_storage: ^10.2.4
  firebase_analytics: ^9.1.6
  # Used to send message
  http: ^0.13.4
  # Work with asynchronous
  async: ^2.8.2
  # Used for internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  # Used for notifications
  flutter_local_notifications: ^9.0.3
  # Used to create vibrations
  vibration: ^1.7.3
  # Used for json management
  json_annotation:
  json_serializable:
  # Used for local file management
  path_provider: ^2.0.2
  # Used for playing sounds
  just_audio: ^0.9.20
  # Keep phone awake
  wakelock: ^0.6.1+2
  # Used for sharing a message or link
  share: ^2.0.4
  # Used to leave a feedback right from the app
  in_app_review: ^2.0.3
  # Used to ask support through mails
  flutter_email_sender: ^5.0.2
  # Used to select profile image
  image_picker: ^0.8.4+4
  # Used to display material segmented control
  material_segmented_control: ^3.1.2
  # Used for circular countdown or chronometer
  sleek_circular_slider: ^2.0.1
  # Used for charts
  charts_flutter: ^0.12.0
  # Used for calendar
  table_calendar: ^3.0.1
  # Used for google sign in
  google_sign_in: ^5.2.1
  # Used for apple sign in
  sign_in_with_apple: ^3.3.0
  is_lock_screen: ^2.0.0
  firebase_app_check: ^0.0.6+11

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - resources/images/
    - resources/sounds/
    - resources/images/general/
    - resources/images/drawer/
    - resources/images/plants/
    - resources/images/sounds/
    - resources/images/welcome/
    - resources/images/login/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Euclid
      fonts:
        - asset: resources/fonts/euclid/EuclidCircularB-Light.ttf
          weight: 300
        - asset: resources/fonts/euclid/EuclidCircularB-Regular.ttf
          weight: 400
        - asset: resources/fonts/euclid/EuclidCircularB-Medium.ttf
          weight: 500
        - asset: resources/fonts/euclid/EuclidCircularB-SemiBold.ttf
          weight: 700
        - asset: resources/fonts/euclid/EuclidCircularB-Bold.ttf
          weight: 900
    - family: Ink
      fonts:
        - asset: resources/fonts/ink/Inkfree.ttf
